### PR TITLE
Initial code base

### PR DESCRIPTION
**Pull request by andycasey**
Yo @davidwhogg and @mkness! I wrote some code.

I had to fork the repository so that I could set up Travis, Coveralls and Scrutinizer. The code includes an abstracted model and has appropriate getters/setters, however we will need to clarify some terms and nomenclature. The models (including sub-classes) are serialisable, and "expensive" components are optionally parallelised by specifying `threads` or a multiprocessing pool when the class is instantiated (e.g., the same parallelism behaviour in `emcee`). The code has 100% test coverage on Python 2.7 and 3.4. 

It's ready for more complex models to be sub-classed (e.g., see [lasso.py](https://github.com/andycasey/AnniesLasso/blob/master/AnniesLasso/lasso.py)), where the methods required for each sub-classed model are `train`, `fit`, and `predict`, and necessary private attributes are `_data_attributes`, `_descriptive_attributes` and `_trained_attributes`. If they're set, all I/O and cross-validation functionality will run from the base model.

I still need to set the documentation pages up, specifically with some getting started/tutorial pages, but functions and classes have informative docstrings.

I wouldn't merge this until I have had a chance to set up documentation (and auto-doc building), but I'm just opening this PR to give you a heads up on what I did these last few days. Next week I'll set up the documentation and look to see what exists in Anna's version that's not implemented here.

### CODE REVIEW

**Comment by mkness** [comment]
Wow! You achieved a heck of a lot in a few days.

I guess you need some more training and test sets then -> Next week; 
please yell mid-week in my general direction if you don't have them by 
then.

**Comment by davidwhogg** [comment]
I don't think I should merge this.  I think I should declare your repo the master.  And then pull-request you my changes.  Objections?

**Comment by andycasey** [comment]
Will do Nessy :+1: 

I have no preference or objection. If you'd prefer to set my repo as master then I will just add you both as collaborators to that repo.

**Comment by davidwhogg** [comment]
Let's do this -- you are now the master.  Can you make sure you merged in my pushed document changes?  I think you did already...

**Comment by andycasey** [comment]
Yep, I made sure I rebased to include your document changes before opening the PR. `andycasey/AnniesLasso` is set as the parent now, and I've added you both as collaborators to that repo.

**Comment by davidwhogg** [comment]
Well done

**Pull request closed without merging**
